// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:953294102600:web:XXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '953294102600',
    projectId: 'kashi-802e8',
    authDomain: 'kashi-802e8.firebaseapp.com',
    storageBucket: 'kashi-802e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:953294102600:android:XXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '953294102600',
    projectId: 'kashi-802e8',
    storageBucket: 'kashi-802e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABKyhQ3MXJFYA3ExCJk-8h38k_tOQwdIw',
    appId: '1:953294102600:ios:803c7a737227d02ffe387d',
    messagingSenderId: '953294102600',
    projectId: 'kashi-802e8',
    storageBucket: 'kashi-802e8.firebasestorage.app',
    iosBundleId: 'com.farukertas.kashi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:953294102600:ios:XXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '953294102600',
    projectId: 'kashi-802e8',
    storageBucket: 'kashi-802e8.appspot.com',
    iosClientId: '953294102600-XXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );
}
